name: CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # 方法3 示例（推荐）
    - uses: actions/setup-node@v3
      with:
        node-version: 18.16.0
        package-manager: pnpm # 自动安装pnpm
    
    # 如果使用方法2：
    # - uses: pnpm/action-setup@v2
    #   with:
    #     version: 8
    
    # 如果使用方法1：
    - run: npm install -g pnpm
    - run: yarn install
    - run: npm install
    
    - run: pnpm install # 现在可以正常使用pnpm命令
    - run: pnpm run build
